export const appLogo = "/images/logo.png"
export const profile = "/images/profile-pic.png"
export const coverPhoto = "/images/cover-photo.png"
export const userProfile = "/images/user-profile.png"
export const arrowDown = "/icons/arrow-down.png"
